# Generated by Django 4.1.7 on 2023-03-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claim_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
