# Generated by Django 4.1.7 on 2023-03-16 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_claim_claim_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blockchain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("network_name", models.CharField(max_length=255)),
                ("network_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block_number", models.IntegerField()),
                ("block_hash", models.CharField(max_length=255)),
                ("previous_block_hash", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField()),
                (
                    "blockchain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.blockchain",
                    ),
                ),
            ],
        ),
    ]
