# Generated by Django 4.1.7 on 2023-03-16 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_blockchain_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="claim",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.claim",
            ),
        ),
        migrations.AddField(
            model_name="block",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.customer",
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="blockchain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.blockchain",
            ),
        ),
    ]
