# Generated by Django 4.1.7 on 2023-03-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_add_claim_reference_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="claim_reference_number",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
