# Generated by Django 4.1.7 on 2023-03-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_claim_claim_amount_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoverageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="claim",
            name="coverage_items",
            field=models.ManyToManyField(to="core.coverageitem"),
        ),
    ]
