# Generated by Django 4.1.7 on 2023-03-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_coverageitem_claim_coverage_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="reasons",
            field=models.TextField(blank=True, null=True),
        ),
    ]
