# Generated by Django 4.1.7 on 2023-03-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_claim_reasons"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="status",
            field=models.CharField(
                choices=[("approved", "Approved"), ("rejected", "Rejected")],
                default="approved",
                max_length=10,
            ),
        ),
    ]
