# Generated by Django 4.2 on 2023-04-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_claim_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="severity",
            field=models.CharField(
                blank=True,
                choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")],
                default="Low",
                max_length=10,
                null=True,
            ),
        ),
    ]
