# Generated by Django 4.2 on 2023-04-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_claim_severity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("to be reviewed", "To Be Reviewed"),
                ],
                default="to be reviewed",
                max_length=20,
            ),
        ),
    ]
